### ISSUE TITLE
Make some handy functions global to allow tinkering from the console

### ISSUE THREAD

**Issue by TodePond** [TodePond/CellPond#100]
Like `registerRule`

**Comment by TodePond** [comment]
wooooooooo!! 

What do you mean by a stamp? :)

**Comment by Magnogen** [comment]
Kind of like a pattern is loaded into the cursor, and then instead of the standard square it produces next time you click on the grid, it loads the pattern that it had.

It can always go back to the standard square after that though.

**Comment by Magnogen** [comment]
AYYYY nice!
