### ISSUE TITLE
Removing a channel from a colour will make new colours not have that channel

### ISSUE THREAD

**Issue by Magnogen** [TodePond/CellPond#106]
![image](https://user-images.githubusercontent.com/25611707/158818486-cf50e5d2-810a-474f-bc1f-67de25c133a6.png)

![image](https://user-images.githubusercontent.com/25611707/158818505-31a79713-cbda-45cb-90cb-0bc76e6786d9.png)

Quirky, but it also means you can't change the colour - perhaps make it default to 0? Thats how it displays the colour in the square.

**Comment by TodePond** [comment]
Sorry to say that this is probably quite an important feature for when channel switching and colour adding/subtracting is implemented. I'll keep it as it is for now, but let's see if it still needs changing when the other stuff is complete!

BTW: you can always just right-click somewhere in the world to pick a new colour (which will have all three channels in)

**Comment by TodePond** [comment]
In fact, there are some bugs that causes it not to clone the channels correctly, when you've moved them around. eg: if you move green to red, the brush colour should also do this!

**Comment by TodePond** [comment]
An update to this: rectangles now lose their 'channel' when dragged off. This is the start of various changes to develop the channel system.

**Comment by TodePond** [comment]
You can now also get a new rectangle from the toolbar!

**Comment by TodePond** [comment]
The colour channel system is more in place now!
