### ISSUE TITLE
Standalone Offline App

### ISSUE THREAD

**Issue by protoknight12** [TodePond/CellPond#203]
Cellpond as a standalone app with offline functionality

**Comment by TodePond** [comment]
That would be great! Currently, you can download the files, and open up `index.html` in a web browser to run it offline.

1. Download the files from here: https://github.com/TodePond/CellPond/archive/refs/heads/main.zip
2. Extract the files.
3. Open `index.html` in a web browser.

**Comment by protoknight12** [comment]
that works

**Comment by protoknight12** [comment]
Where is the standalone?

**Comment by TodePond** [comment]
Sorry I'm just gonna keep it as a web app, but you can always download it and run `index.html` :)

**Comment by protoknight12** [comment]
Understandable
