### ISSUE TITLE
🔮 Spellular Automata

### ISSUE THREAD

**Issue by TodePond** [TodePond/CellPond#204]
# Warning: Spoilers

Make a new video called 🔮 **Spellular Automata**!

## Music
- [x] Sleepwalker (Extended Mix) - Tinlicker
- [x] Love You More (Andrew Bayer & Genix In My Next Life Mix) - Andrew Bayer, Ane Brun, Genix
- [x] Love You More - Andrew Bayer, Ane Brun

https://pixabay.com/sound-effects/thunder-25689/

## Code: General
- [x] PaintPond
- [x] Cursors
- [x] Transitions
- [x] Visuals
- [x] Hexagon (chance)
- [x] Hexagon (adding/subtracting)
- [x] Joins
- [x] Split/Merge Compatibility
- [x] Performance

## Code: Parts
- [x] Tode: Fire
- [x] Berd: Flame
- [x] Tode: Lightning
- [x] Berd: Tree
- [x] Tode: Fractal
- [x] Berd: SUPER Fractal
- [x] Tode: World
- [x] Berd: World
- [x] Tode: Star
- [x] Berd: Beautiful Flower
- [x] Tode: Pink Sand
- [x] Berd: Rainbow
- [x] Tode: Rainbow

## Script
- [x] Intro
- [x] Tode: Fire
- [x] Berd: Flame
- [x] Tode: Lightning
- [x] Berd: Tree
- [x] Tode: Fractal
- [x] Berd: SUPER Fractal
- [x] Tode: World
- [x] Berd: World
- [x] Fakeout
- [x] Tode: Star
- [x] Berd: Beautiful Flower
- [x] Tode: Pink Sand
- [x] Berd: Rainbow
- [x] Tode: Rainbow
- [x] Outro
- [x] Credits

## Voice
- [x] Intro
- [x] Tode: Fire
- [x] Berd: Flame
- [x] Tode: Lightning
- [x] Berd: Tree
- [x] Tode: Fractal
- [x] Berd: SUPER Fractal
- [x] Tode: World
- [x] Berd: World
- [x] Fakeout
- [x] Tode: Star
- [x] Berd: Beautiful Flower
- [x] Tode: Pink Sand
- [x] Berd: Rainbow
- [x] Tode: Rainbow

## Transitions
- [x] Intro
- [x] Tode: Fire
- [x] Berd: Flame
- [x] Tode: Lightning
- [x] Berd: Tree
- [x] Tode: Fractal
- [x] Berd: SUPER Fractal
- [x] Tode: World
- [x] Berd: World
- [x] Fakeout
- [x] Tode: Star
- [x] Berd: Beautiful Flower
- [x] Tode: Pink Sand
- [x] Berd: Rainbow
- [x] Tode: Rainbow
- [x] Outro
- [x] Credits

## Video
- [x] Intro
- [x] Tode: Fire
- [x] Berd: Flame
- [x] Tode: Lightning
- [x] Berd: Tree
- [x] Tode: Fractal
- [x] Berd: SUPER Fractal
- [x] Tode: World
- [x] Berd: World
- [x] Fakeout
- [x] Tode: Star
- [x] Berd: Beautiful Flower
- [x] Tode: Pink Sand
- [x] Berd: Rainbow
- [x] Tode: Rainbow
- [x] Outro
- [x] Credits

## Promo
- [x] Teaser
- [x] Reviews
- [x] Trailers
- [x] Spoiler Trailers

**Comment by TeraByte-Official** [comment]
Can't wait to see the video when it comes out, also is the mysterious disappearance of the Diamond intentional?

**Comment by TodePond** [comment]
Hello :) I'm doing some big changes to it at the moment, and I'm replacing the diamond with some simpler shapes. The new diamond won't have the add/subtract functionality. A new octagon shape will do that instead. 

And yes, paddles work differently now. You can't lock them. To turn a rule off/on, click on the triangle. To clone shapes, you now need to right-click and drag instead.

The Down Arrow will let you make rules with multiple steps. You'll also be able to change the chance of a rule happening with octagons. That's the main new stuff I think :D

**Comment by TeraByte-Official** [comment]
Oh. Thank you, Tode!

**Comment by TodePond** [comment]
Ok I think I've done all the visual/UI redesigning I want for now. Next up I'm gonna try to make all the elements for the video and see what else I really need.

**Comment by JPgamers150** [comment]
How do I combine cells in the editor to occupy one cell?

**Comment by TodePond** [comment]
Do you mean like this? 
![image](https://user-images.githubusercontent.com/15892272/192240187-e0e4ec66-c7c8-4df5-987a-eaba99518937.png)

Arrange the squares how you want on a paddle.
Then right-click and drag the paddle to get your combined cell.
(or you can left-click the paddle, and pull down a square from the toolbar at the top of the screen)

**Comment by TodePond** [comment]
Lightning done

**Comment by TodePond** [comment]
Tree, Fractal, Super Fractal done

Did a re-prioritise of some issues ahead of the video - some moved to the "AFTER VIDEO 3" milestone if the video doesnt strictly need them

**Comment by TodePond** [comment]
Joins all finished now

**Comment by TodePond** [comment]
add+subtracting with hexagons now works. Just doing some cleaning up now

**Comment by TodePond** [comment]
Star done

**Comment by TodePond** [comment]
World done!

**Comment by TodePond** [comment]
Rainbow 1 done

**Comment by TodePond** [comment]
ALL CODE DONE!!

**Comment by TodePond** [comment]
Script for Intro done

**Comment by TodePond** [comment]
Fire script done

**Comment by TodePond** [comment]
Flame script done

**Comment by TodePond** [comment]
Lightning script done

**Comment by TodePond** [comment]
Tree script done

**Comment by TodePond** [comment]
Fractal script done

**Comment by TodePond** [comment]
Super fractal script done

**Comment by TodePond** [comment]
Credits script done

**Comment by TodePond** [comment]
World 1 script done

**Comment by TodePond** [comment]
Fakeout script done

**Comment by TodePond** [comment]
Star and Flower script done

**Comment by TodePond** [comment]
Pink sand script done

**Comment by TodePond** [comment]
Rainbow 1 script done

**Comment by TodePond** [comment]
Rainbow 2 script done

**Comment by TodePond** [comment]
ALL THE SCRIPT IS DONE!

**Comment by TodePond** [comment]
Teaser trailer done

**Comment by TodePond** [comment]
Gonna release the teaser video on Thursday

**Comment by TodePond** [comment]
Voice for intro, fire and flame done

**Comment by TodePond** [comment]
Lightning voice done

**Comment by TodePond** [comment]
Tree & Fractal voice done

**Comment by TodePond** [comment]
Super Fractal voice done

**Comment by TodePond** [comment]
World 1 and World 2 done

**Comment by TodePond** [comment]
Fakeout voice done

**Comment by TodePond** [comment]
ALL VOICEOVER DONE!!!!!!!!

**Comment by TeraByte-Official** [comment]
अपि च क्रीडकानां कृते आरामदायकं द्विचक्रिकायाः आवश्यकता वर्तते । प्रत्येकं समये, सा कण्ठः स्तरसीमाः प्रेरयति। इदं केवलं फुटबॉल-क्रीडायां निर्मितम् अस्ति । एकः बसः तावत् पादकन्दुकक्रीडाङ्गणं सुलभम् अस्ति। आयु स्तर परत। वैद्यकार्यालये बहु रुचिः वर्तते। सर्वे स्मार्टफोनस्य भिन्नं प्रदर्शनं गृह्णन्ति। कम्पमानः कूपः, यस्य महत्तमस्य टिन्सिडेंटस्य आवश्यकता वर्तते, सः सर्वदा स्वच्छः भवितुम् इच्छति, एकः तथा हसति। पुरुषवाहः इदानीं शरैर्भूषयति उल्का मृदुः

**Comment by TodePond** [comment]
I'm back from holiday now - all cursors done

**Comment by TodePond** [comment]
Intro video done

**Comment by TodePond** [comment]
Intro transitions done

**Comment by TodePond** [comment]
Credits done (except for patrons)

**Comment by TodePond** [comment]
I recorded all transitions but they suck so I'll do it again better tomorrow

**Comment by TodePond** [comment]
I re-recorded the first half transitions. They're better now. I also made the video for fakeout

**Comment by TodePond** [comment]
I re-recorded voice over for the first few sections to make it ramp up more gradually

**Comment by TodePond** [comment]
All transitions recording done - including second part - now need to do starfields

**Comment by TodePond** [comment]
Transitions finished for fire, flame, lightning, tree, fractal

**Comment by JPgamers150** [comment]
A miscellaneous topic, do not touch the caca.

:poop:

**Comment by TodePond** [comment]
Loudness effects of voice of first part is producing some weird audio artifacts - needs fixing

and the transition to second part voiceover sounds weird - needs fixing

**Comment by TodePond** [comment]
Improved the voice effects + transition

**Comment by TodePond** [comment]
All core transitions done

**Comment by TodePond** [comment]
ALL transitions done

**Comment by TodePond** [comment]
I tweaked the voiceover from part 1 -> part 2 a bit more - I think it was messing up because of the denoiser

**Comment by TodePond** [comment]
Lightning video done

**Comment by TodePond** [comment]
Tree video done

**Comment by TodePond** [comment]
Fractal video done

**Comment by TodePond** [comment]
Notes from watching back: final chain of clips of flame look janky. maybe make the last one's world much bigger? and check timing

**Comment by TodePond** [comment]
on second watch, the flame clips are fine
but a couple of things: 

framerate of fire starfield too low
you can see through tode's eye in fire transition

also: some resolutions of starfields are a bit low (eg: tree) but that might be ok!

**Comment by TodePond** [comment]
I fixed all those things!

**Comment by TodePond** [comment]
Super fractal video done

**Comment by TodePond** [comment]
Notes:

final clips of flame still dodgy - move the final one right a bit?

fractals zoom out (+ in?) a bit too fast

add a fake berd cursor to super fractal clips

**Comment by TodePond** [comment]
also: 

fire stars in outro too low framerate

one of berd's stars still has the stutter from before in the credits

**Comment by TodePond** [comment]
all fixed

**Comment by TodePond** [comment]
World 1 video done

**Comment by TodePond** [comment]
World 2 video done

**Comment by TodePond** [comment]
Star video done

**Comment by TodePond** [comment]
Flower video done!

**Comment by TodePond** [comment]
Pink Sand done

**Comment by TodePond** [comment]
Rainbow 1 video done

**Comment by TodePond** [comment]
notes: remove script overlay from rainbow 1

**Comment by TeraByte-Official** [comment]
5 more tasks! I can't wait!

**Comment by TodePond** [comment]
Rainbow 2 done

**Comment by TodePond** [comment]
The video is Done!!

releasing it tomorrow morning

**Comment by TeraByte-Official** [comment]
Yay!!!

**Comment by TodePond** [comment]
I've now made all the promotional materials too. Everything's finished!!

Next video: 📕 [**Define Define**](https://github.com/TodePond/MeanPond/issues/1)
