### ISSUE TITLE
Alternative octagon number shape

### ISSUE THREAD

**Issue by TodePond** [TodePond/CellPond#206]
The rectangle sucks for certain numbers.

It isn't clear from looking at it what number is (the greys are too similar).
And it can't do negative numbers.

There should be a new number shape, an octagon.

Rectangle is our unsigned integer.
Octagon is our signed integer.

As the number gets bigger, it could 'fill in' around the shape, like a clock/timer. By default, half is filled in, representing 0. As the clock goes round clockwise, it goes up to +4. As it goes anti-clockwise, it goes down to -4. (So, still 9 possible values).

**Comment by TeraByte-Official** [comment]
Wait, don't diamonds have _9_ possible values?

**Comment by TodePond** [comment]
near enough :)

**Comment by TodePond** [comment]
Gonna make it a hexagon instead
![image](https://user-images.githubusercontent.com/15892272/191721876-af5545d6-2691-4d88-aa77-babecc21ab83.png)

**Comment by TeraByte-Official** [comment]
But what will happen to MY hexagon?

**Comment by TodePond** [comment]
That can be a different shape :D

**Comment by TodePond** [comment]
Hexagons now work for setting the chance of a rule happening

**Comment by TodePond** [comment]
Gonna close this now and split into smaller issues
