### ISSUE TITLE
Glitch: Freaky Red

### ISSUE THREAD

**Issue by 100xCode** [TodePond/CellPond#218]
When playing with CellPond, I discovered that using the nested blocks feature used in the 🤖[Nothing](https://www.youtube.com/watch?v=sQYUQNozljo&t=19s&ab_channel=TodePond) video to make tadpoles, you can nest four blocks as one and things go fine:

<img width="669" alt="Screen Shot 2022-08-25 at 5 19 03 PM" src="https://user-images.githubusercontent.com/104718768/186770953-e58b3a77-f22c-4ec6-9aed-496aad1ab24f.png">

But nest four of those nested "blocks" and the element itself keeps its color but turns red when drawn on-screen:

<img width="715" alt="Screen Shot 2022-08-25 at 5 19 44 PM" src="https://user-images.githubusercontent.com/104718768/186770937-0324f01b-ce94-45ea-8cf4-48c8c18c9dc8.png">

Along with that, the other shapes (such as that triangle) also turn red for that element:

<img width="150" alt="Screen Shot 2022-08-25 at 5 24 55 PM" src="https://user-images.githubusercontent.com/104718768/186771740-d7d3c193-41ce-4cc4-93ee-3111f55e131b.png">

This is not to be confused with an element made of 16 blocks, which stays intact but instead does this:

<img width="706" alt="Screen Shot 2022-08-25 at 5 23 49 PM" src="https://user-images.githubusercontent.com/104718768/186771786-b2e6b4e0-9ad9-47f9-ae73-704b82e49095.png">

Freaky.

**Comment by 100xCode** [comment]
🤦🏾 I just noticed this is a copy of last week's #215

**Comment by TodePond** [comment]
hey thank you! this is the same as #215 but you've done a very clear explanation of it, which is very helpful for me, so thanks :)

**Comment by 100xCode** [comment]
You're welcome @TodePond.

**Comment by TodePond** [comment]
I believe this doesn't happen any more now
