### ISSUE TITLE
Grouped squares are strange

### ISSUE THREAD

**Issue by TeraByte-Official** [TodePond/CellPond#257]
Let's say you have two cells, red and blue. You want them both to fall down, so you put this rule on a paddle:

![rule](https://user-images.githubusercontent.com/105992370/192124835-d89a4227-def0-40a0-a684-bc5566e84e55.png)

Now, you put down both cells, but notice blue isn't falling down. This is because you put red in the group first.

Basically, grouped squares only affect the first item.

Edit: Nevermind, groups don't work at all anymore.

**Comment by TodePond** [comment]
Yes it was broken by some of the redesign, I'm gonna fix it this week :)

**Comment by TodePond** [comment]
It seems like they're working to me, but the visuals of the squares are all messed up.

![image](https://user-images.githubusercontent.com/15892272/192557595-64302790-d2ab-4d95-8fbd-b9f030eec5b8.png)

**Comment by TodePond** [comment]
This should be fixed now: #263

Visuals are still broken though: #193
