### ISSUE TITLE
Colour OR operator

### ISSUE THREAD

**Issue by TodePond** [TodePond/CellPond#26]
Allow a colour to either be one colour or another!

**Comment by TodePond** [comment]
This is important because I need it to introduce the concept of colours potentially being more than one colour in the video.

**Comment by TodePond** [comment]
I should probably do split-cell squares before this one. Otherwise I'll probably have to redo parts of it

**Comment by Magnogen** [comment]
Perhaps when the OR operator is on the right side (output), it should pick a random one from the range? (unless its stamped to be the same as a square on the right)

This would make it similar to ranges, just with more ease of use

**Comment by TodePond** [comment]
It's intended to work the same ways as ranges yes! On the backend, it'll probably work exactly the same way - just differently in the UI! In the text representation of the language, it'll work the same way as ranges

**Comment by TodePond** [comment]
You can now combine squares together. Still more to do.

- [ ] Draw: the joined square should cycle through its colours
- [ ] Value: the joined square should output a joined dragon array
- [ ] Rule: the registered rule should know what to do with the joined dragon array
