### ISSUE TITLE
Square in toolbar isn't quite clean

### ISSUE THREAD

**Issue by TeraByte-Official** [TodePond/CellPond#273]
![SquareInToolbarIsNotClean](https://user-images.githubusercontent.com/105992370/193084462-6f7fcaf6-781e-43c4-8c53-cf8ed27f15fb.jpg)
Above: Toolbar square
Below: Orphaned square

**Comment by TodePond** [comment]
You're right :) planning to fix that this week hopefully #272

**Comment by TodePond** [comment]
Done! 7b2d1ff45812669b4dfeeebd90cec8df5675f2a1
