### ISSUE TITLE
Replace hexagons+diamonds with triangles

### ISSUE THREAD

**Issue by TodePond** [TodePond/CellPond#281]
Too late to do this for the video now, but in the future:

Pointing up = Add 1
Pointing down = Subtract 1
Pointing right = Channel to the right
Point left = Channel to the left

related: #249 

Bonus: Consider alternative for hexagon chance values

**Comment by TodePond** [comment]
done!

**Comment by JUSTINEEZEKIEL** [comment]
how do u copy the channel of rg and b

**Comment by TodePond** [comment]
Point the triangle arrow left or right
