### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'width')

### ISSUE THREAD

**Issue by juh9870** [TodePond/CellPond#288]
![image](https://github.com/TodePond/CellPond/assets/15922601/7f00de1d-6a48-441a-9916-b26566ee74f8)

randomly happened during gameplay

**Comment by TodePond** [comment]
Hey can you figure out how to reproduce this reliably? If you can, I'll be able to fix it

**Comment by juh9870** [comment]
![image](https://github.com/TodePond/CellPond/assets/15922601/9ceba03c-94ce-4f8c-9617-9ae21607ffc4)
Looks similar enough. When the output rule has an "empty" cell (without a small black dot) and you try to stamp it, app breaks

**Comment by TodePond** [comment]
Ah found it: https://github.com/TodePond/CellPond/issues/161

**Comment by TodePond** [comment]
Unless I'm understanding wrong? :)
