### ISSUE TITLE
commonly, the rules you set, just, invalidate.

### ISSUE THREAD

**Issue by usernameisrobert** [TodePond/CellPond#292]
the cells in the rules you set, move, slightly invalidating the rule

**Comment by TodePond** [comment]
can you show me a screenshot? :) and can you figure out how to reliably reproduce this? I think I might know whats going on

**Comment by usernameisrobert** [comment]
to reliably recreate this, simply replace a block form a rule and keep doing that untill you see something ike this;

![Screenshot 2023-06-18 084147](https://github.com/TodePond/CellPond/assets/120859934/89dec008-09b6-4ecb-a688-0d2850014a86)

**Comment by usernameisrobert** [comment]
hello?

**Comment by MostLongestName** [comment]
You remove the rule and put it back, it happens.

**Comment by TeraByte-Official** [comment]
As a fix for this bug, maybe check if a square is misaligned, and if it is, just align it again.

Not very complicated.

**Comment by Pcyahcn142857** [comment]
THis is already in 336 and 316 Somebody close this and 316 @TodePond

**Comment by TodePond** [comment]
a dx and dy need to be set to 0 somewhere if anyone wants to take a crack at fixing it

**Comment by usernameisrobert** [comment]
> THis is already in 336 and 316 Somebody close this and 316 @TodePond

ok, sure, I was not sure what to search to check if this is a duplicate, so I posted it anyways, go to #336 for the solution ig
