### ISSUE TITLE
How do you change brush size?

### ISSUE THREAD

**Issue by Jeremy5909** [TodePond/CellPond#293]
It seems so simple but I cant figure it out

**Comment by TodePond** [comment]
This might have broken recently. Usually, it's Shift + mousewheel. What browser + OS are you using?

**Comment by Jeremy5909** [comment]
Ah that did it. Sorry i just couldnt figure that out. Sorry for wasting time - thanks.

**Comment by avidrucker** [comment]
How about for Linux? On my Linux Mint machine that keybinding does a local magnification of the screen
