### ISSUE TITLE
How in the world did master TodePond Make this part in their newest video??

### ISSUE THREAD

**Issue by Jeremy5909** [TodePond/CellPond#295]
https://youtu.be/ZMklf0vUl18?t=176 How did they make this seemingly infinite quality sand?? I get the basic idea but I can't get it right

**Comment by TodePond** [comment]
It's a different project https://github.com/TodePond/SandLab

**Comment by Jeremy5909** [comment]
Ah thanks. Is it possible on cellpond ya think or nah
prolly not or atleast not to easy

**Comment by TodePond** [comment]
its not possible to code it with the visual editor in cellpond. the underlying engine can support it, but there's no useful API for it. SandLab is kinda like my in-progress sequel to cellpond. It lets you do madder stuff! (but theres no visual editor for it yet)

**Comment by Jeremy5909** [comment]
What would it take to do so? And how would I do it in sandlab? I'm learning abt it rn
