### ISSUE TITLE
Add/Subtract Color

### ISSUE THREAD

**Issue by Jeremy5909** [TodePond/CellPond#297]
After the removal of diamonds, is there a way to add or subtract color like we could?

**Comment by TodePond** [comment]
```yes the hexagon but it's a secret```

**Comment by Jeremy5909** [comment]
Isn't the hexagon a chance operator? How does it work like the diamond?

**Comment by Muhtasim-Rasheed** [comment]
issue creator @Jeremy5909 said "Diamonds" but Hexagon operator is chance operator.

**Comment by TodePond** [comment]
Hexagons do more than chance :) try placing it into a colour

**Comment by protoknight12** [comment]
i dont think you can place it onto a colour

**Comment by TodePond** [comment]
If you try these steps and let me know which part goes wrong, I can help:

1. Click on the square to open it up.
2. Pull off one of the wide rectangles from the square's panel.
3. Place a hexagonal where the wide rectangle was.

**Comment by TodePond** [comment]
Covered by #281
