### ISSUE TITLE
Bring Diamond Back.

### ISSUE THREAD

**Issue by Muhtasim-Rasheed** [TodePond/CellPond#301]
So I was just watching TodePond's "Nothing" video and doing the things that was described there. But TodePond said "diamond operator" and I couldn't find it anywhere. So, Bring Diamond Back.

**Comment by TeraByte-Official** [comment]
TodePond broke the diamond and had to remove it when he was making Spellular Automata.

**Comment by TodePond** [comment]
Covered by #281
