### ISSUE TITLE
How do I scroll through palletes?

### ISSUE THREAD

**Issue by idr1ss** [TodePond/CellPond#302]
Currently theres a limit to how many palletes i can create and i don't know how to fix this. Please help me!

**Comment by VINDI777** [comment]
what is a "palette"?

**Comment by TeraByte-Official** [comment]
I think you mean paddles?
That's simple: just ctrl+scroll to zoom, and alt+scroll to scroll.

**Comment by TodePond** [comment]
Currently you can hold 'alt' or 'option' and scroll the mouse wheel. I think that's it
We should make it scrollable in the normal way though 
Duplicate of #53
