### ISSUE TITLE
Middle-clicking produces "Error loading rules... Sorry! Please contact @todepond :)"

### ISSUE THREAD

**Issue by 5ucur** [TodePond/CellPond#304]
Middle-clicking on the page produces an alert box with the content as in the title. Clicking okay on that removes all the paddles, adds all the shapes up top, and as far as I know only a page reload fixes the issue.

Further middle-clicking gives the alert again and again. Preventing the page from producing any more alerts doesn't help. It only removes the alert, but after a reload and a new middle-click, the paddles get removed again.

I tend to middle-click as I'm used to that being the pan control on many things - it doesn't have to pan on this site, but at least not making this error would be nice.

System info:
Linux, 6.1.12-arch1-1
Firefox 110.0

If any other info is needed, just ask!

**Comment by TodePond** [comment]
Ah I think this is caused by middle-click paste on Linux. I should prevent paste some day

**Comment by 5ucur** [comment]
Probably is, as `Ctrl + V` gives the same error! I didn't even think of the pasting being a problem.
