### ISSUE TITLE
Help menu

### ISSUE THREAD

**Issue by Muhtasim-Rasheed** [TodePond/CellPond#331]
New people might get lost, so adding a help menu may help, especially for new people (Thats literally what it does).
This is what I made for the help button:

![pixil-frame-0](https://github.com/TodePond/CellPond/assets/118351661/c531a42a-0a1f-4177-a4fa-275f97562a8d)

**Comment by TodePond** [comment]
Maybe it could be in the top right of the screen!

**Comment by TeraByte-Official** [comment]
I think this is a pretty good idea!

**Comment by Muhtasim-Rasheed** [comment]
Thx =D
