### ISSUE TITLE
Feature request: Saving locally and via URL parameters

### ISSUE THREAD

**Issue by AverseABFun** [TodePond/CellPond#338]
I want to make something super cool in this, but the fact that there is no saving really limits what you want to do when you just reload it vanishes. I will probably be working on this so I can pull request, and I'll link the pull request here if/when it happens.

**Comment by TodePond** [comment]
Hey I reckon it will be hard to fit in enough information to fit into URL parameters, which have a maximum size.

You can save / load by doing these things:

Ctrl + S: Save
Ctrl + C: Copy to clipboard
Ctrl + O: Load
Ctrl + V: Paste to cellpond
Drag and drop file onto cellpond: Load

One area to explore might be saving things into `localStorage`? Good luck, have fun!

**Comment by AverseABFun** [comment]
_what_
I did not know! cool.
