### ISSUE TITLE
Cool information(not a enhancement or bug or anything, just a cool thing)

### ISSUE THREAD

**Issue by AverseABFun** [TodePond/CellPond#339]
CellPond is Turing complete, as you can implement the game of life in it, which is Turing complete!

**Comment by AverseABFun** [comment]
(er, conways game of life rather)

**Comment by Jeremy5909** [comment]
how

**Comment by AverseABFun** [comment]
By making all the necessary rules

**Comment by Jeremy5909** [comment]
im not sure if this is possible or at least super easy because of how cellpond works (asynchronous and what not)

**Comment by AverseABFun** [comment]
I believe it is _theoretically_ possible, but it definitely isn't very easy.
