### ISSUE TITLE
CellPond import/export

### ISSUE THREAD

**Issue by Pcyahcn142857** [TodePond/CellPond#343]
Hello! I'm new and want to contribute :) I like your channel, but I can't support you on Patreon because I don't have a credit card. I think it would be good if we could import all the data of the paddles (like in a text file) and also have the program import the data of the paddles back by decoding the text file. I will add a snippet of code later on this thread if I have time. Hope you are doing well on your channel!

**Comment by TodePond** [comment]
hey thanks! you can do this by hitting 

Ctrl/Cmd+S

and

Ctrl/Cmd+O to load


(or drag on a file to load it)

or Ctrl/Cmd+C to copy to clipboard
or Ctrl/Cmd+V to load from clipboard

**Comment by Pcyahcn142857** [comment]
Ok, thanks for the update! Now CellPonders (I made that up) won't have to reset their progress every time they shut down their computer. I'll suggest new ideas if I have any!

**Comment by Pcyahcn142857** [comment]
Hey, how about a Discord server to post creations? And if you still have the diamond code, I'll try to debug it.

**Comment by TodePond** [comment]
oh hey by the way, i do have a discord which is for paying supporters of my patreon: https://patreon.com/todepond
