### ISSUE TITLE
Rule with 3x3 multi-squares gets applied rotated, merged and stretched

### ISSUE THREAD

**Issue by Paalui** [TodePond/CellPond#354]
![image](https://github.com/TodePond/CellPond/assets/174252670/2e735cc1-30ba-4f04-977d-cba3bcca22b1)

<img src="https://github.com/TodePond/CellPond/assets/174252670/87eac6c1-aba6-448b-80f7-d331165705e9" height="120" />
<img src="https://github.com/TodePond/CellPond/assets/174252670/b0b769d9-b7a3-43d7-9a81-df14999c479d" height="200" />

Also when you try to erase it with the brush it stary around partially. (right is after you move/zoom)
![image](https://github.com/TodePond/CellPond/assets/174252670/651fc39a-f13a-4a84-9d02-38711fd06636)

Also also when you try to regenerate the grid after it doesn't work.

File: [bug2.json](https://github.com/user-attachments/files/16090887/bug2.json)

With the simpler case i tried it only merged some cells incorrectly:
It displays it correct at first but after you move/zoom shows it broken.

![image](https://github.com/TodePond/CellPond/assets/174252670/94abdccd-4c02-4a65-b631-4d014e158240)
![image](https://github.com/TodePond/CellPond/assets/174252670/f92653b0-c7f6-4bb3-8923-bd462b9727d2)

File: [bug3.json](https://github.com/user-attachments/files/16091093/bug3.json)

**Comment by TodePond** [comment]
I'm wondering if this (and maybe #353) are due to float inaccuracies. Could probably (maybe) scale everything up to give it a bigger window of accuracy.

**Comment by Paalui** [comment]
If its because of float inaccuracies i would expect it to be different when trying it with different world sizes

**Comment by TodePond** [comment]
its quite possible that its my shitty code instead :)

**Comment by Paalui** [comment]
I think #353 is because of inaccuracies and perhaps some of this too. But i don't see how the 2nd example wtih the 2way split cells can be due to it. Because it only divides by 2.

**Comment by TodePond** [comment]
fixed by @Paalui
