### ISSUE TITLE
Chance shape?

### ISSUE THREAD

**Issue by TodePond** [TodePond/CellPond#96]
Could there be something you attach to a paddle to change the chance of that rule happening?

**Comment by Magnogen** [comment]
Maybe a hexagon? Then each triangle could represent a 1 in 6 chance, and clicking it could cycle it?

Maybe an octagon? Then It'd be 1 in 8!

I think going above 8 might be a bit difficult to use and see, especially for smaller screens though. 🤔

**Comment by Magnogen** [comment]
Perhaps it could be dragged onto the end, like the symmetry circle, and then that would move down to make room for it?

I'm not sure, if I come up with something else, I'll let you know!

**Comment by TodePond** [comment]
What about the top of the paddle?

**Comment by Magnogen** [comment]
It could be!

**Comment by TodePond** [comment]
Yeah maybe any 'modifiers' like the circle and the chance shape could be placed on the right edge of the paddle 🤔

**Comment by Magnogen** [comment]
That's a good idea! Perhaps in stead of the chance shape meaning there's a probability that a rule _doesn't_ happen, perhaps it could give it a weight, kind of like a way of saying "this rule is three times as likely to be chosen if there's more than one outcome"?

A simple way to do this would just be to duplicate the rule a bunch of times, but that can be cumbersome. Could this work as an alternative?

**Comment by TodePond** [comment]
I had an idea - what if you can just drag a number onto the edge of a paddle! The number determines the chance of it happening.

**Comment by TodePond** [comment]
You can now drag rectangles onto shapes to set the chance of the paddle happening! This is what the different numbers do:

9 = always
8 = one in 2
7 = one in 4
6 = one in 8
5 = one in 16
4 = one in 32
3 = one in 64
2 = one in 128
1 = one in 256
0 = never
