### ISSUE TITLE
Empty squares on the right should mean it's unchanged

### ISSUE THREAD

**Issue by Magnogen** [TodePond/CellPond#97]
When you put a range square on the left, and then leave the corresponding square on the right blank - no square at all, it does some interesting behaviour.

I think it should leave that cell alone, keeping the colour it was, but at the moment it pretends the range was there, and converts it to a random colour in that range.

![a gif showing a rule that has a range that covers all colours on the left, and an empty slot on the right - it results in colourful noise in the automata grid](https://user-images.githubusercontent.com/25611707/158347510-21b9a361-d725-44a2-bf12-b6f4add11d36.gif)

**Comment by TodePond** [comment]
good idea! I think I'll make a new instruction on the backend that's "DO_NOTHING" or something! Currently it does the "RECOLOUR" instruction by default.

this also shows another bug -> the colour of numbers in a range should be maintained. It's on my list of issues to fix this! (range identity should be maintained)

**Comment by Magnogen** [comment]
ahhh right, yeah the only range i used in this was one that spans from black to a dark red and it resulted in all manner of colours

![image](https://user-images.githubusercontent.com/25611707/158351625-14502d3d-2491-4058-8f3d-471c1adcdd9e.png)

**Comment by TodePond** [comment]
This is the issue: #21

**Comment by TodePond** [comment]
No it's ok this is another thing :) It does recolour stuff, which it probably shouldn't

**Comment by TodePond** [comment]
So, empty squares are now automatically set to three diamonds: 🔴🟢🔵

So I reckon that should keep cells the same??? But maybe it has some weird behaviour (rightly or wrongly) due to auto-stamping or stamping??? I think a new "do nothing" instruction would still be a good idea to make sure there is no weird behaviour going on.
