### ISSUE TITLE
Playback / step controls

### ISSUE THREAD

**Issue by Magnogen** [TodePond/CellPond#98]
Pressing space works for playing and pausing the automata, but sometimes I can't figure out if it's currently playing, or is paused!

Perhaps a play/pause icon to show what it's doing? If you add an icon for it, you could also add click functionality, then people don't have to press space if they don't want to. (And it'll work for mobiles!)

Some other ideas for playback controls:
- Perhaps a way to only advance one frame (all the pixels in the grid, shuffled as it usually would), to have finer control than quickly playing and pausing again.
- And a way to only play one event (a single successful rule)? Then explaining how the rules work would be clearer and easier.

**Comment by TodePond** [comment]
![image](https://user-images.githubusercontent.com/15892272/163819311-cc888a74-f906-48e8-b56d-577eba31975e.png)

**Comment by TodePond** [comment]
No step controls! Covered by #178

**Comment by TodePond** [comment]
![image](https://user-images.githubusercontent.com/15892272/163819557-ce206f39-97da-4c06-8e64-4734017b77ed.png)

**Comment by Magnogen** [comment]
Nice diagram! Interesting how it's incorporated with the rest of the UI!

How would it work if you put a diamond in there...?

**Comment by TodePond** [comment]
A diamond would make the speed depend on the current brush colour :)

(that's what diamonds use as a default)

**Comment by TodePond** [comment]
merged into #11

**Comment by MostLongestName** [comment]
> Pressing space works for playing and pausing the automata, but sometimes I can't figure out if it's currently playing, or is paused!
> 
> Perhaps a play/pause icon to show what it's doing? If you add an icon for it, you could also add click functionality, then people don't have to press space if they don't want to. (And it'll work for mobiles!)
> 
> Some other ideas for playback controls:
> 
> * Perhaps a way to only advance one frame (all the pixels in the grid, shuffled as it usually would), to have finer control than quickly playing and pausing again.
> * And a way to only play one event (a single successful rule)? Then explaining how the rules work would be clearer and easier.

Temp solution: Place some sand and see if it falls (maybe put it in a small box to remove easily)
