### ISSUE TITLE
It's not obvious whether a slot is empty or black

### ISSUE THREAD

**Issue by TodePond** [TodePond/CellPond#99]
Maybe change black squares to have a lighter border to make the difference more clear

**Comment by Magnogen** [comment]
Maybe have diagonal lines going through empty slots?

Some thing like this?

![idea](https://user-images.githubusercontent.com/25611707/158356339-128eab3c-e918-4dc3-a566-96c43ad8c1fa.png)

**Comment by TodePond** [comment]
I've done a change to make it look like that. Not entirely sure about it though! Not sure it fits the style, but maybe something similar

**Comment by TodePond** [comment]
https://twitter.com/todepond/status/1503798390173454336

**Comment by TodePond** [comment]
Closing this because I think it's ok for now!
